In [13]:
import numpy as np

In [14]:
a = np.array([1,2,3,4])

In [15]:
type(a)




numpy.ndarray

In [16]:
a.shape

(4,)

In [17]:
a.size

4

In [18]:
b = np.array([(1,2,3,4),(4,5,6,7)])

In [19]:
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [20]:
b.shape

(2, 4)

In [21]:
b.size

8

In [22]:
a.sum()

10

In [23]:
a.prod()


24

In [24]:
a.min()


1

In [25]:
a.max()


4

In [26]:
print(b)


[[1 2 3 4]
 [4 5 6 7]]


In [27]:
b= b.reshape(4,2)


In [28]:
print(b)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [29]:
b.shape

(4, 2)

In [30]:
b[0,1]

2

In [31]:
b[1,1]

4

In [32]:
b[0,0]

1

In [33]:
b[1,1]

4

In [34]:
c= np.array([(1,2,3,4),(4,5,6,7)])
c

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [35]:
c.sum(axis=0)

array([ 5,  7,  9, 11])

In [36]:
c.sum(axis=1)

array([10, 22])

In [37]:
import pandas as pd
df=pd.DataFrame({'col1':['A','B','B','A',],'col2':[1,2,2,3]})

In [38]:
df

col1  col2
0    A     1
1    B     2
2    B     2
3    A     3

In [39]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [40]:
df[df.duplicated()]

col1  col2
2    B     2

In [41]:
df1 = df.drop_duplicates()

In [42]:
df1

col1  col2
0    A     1
1    B     2
3    A     3

In [43]:
df2=df1.reset_index()

In [44]:
df2

index col1  col2
0      0    A     1
1      1    B     2
2      3    A     3

In [45]:
df3=df2.drop('index',axis=1)

In [46]:
df3

col1  col2
0    A     1
1    B     2
2    A     3

In [48]:
# prompt: NumPy Array creation using array() Function

import numpy as np

# Create a NumPy array from a list
my_array = np.array([1, 2, 3, 4, 5])

# Print the array
print(my_array)

# You can also create arrays with different data types
my_float_array = np.array([1.0, 2.0, 3.0])
my_float_array

[1 2 3 4 5]


array([1., 2., 3.])

In [49]:
# prompt: array attributes examples , more examples

# More examples of array attributes and operations

# Create a 3x3 array filled with zeros
zeros_array = np.zeros((3, 3))
print(zeros_array)

# Create a 2x4 array filled with ones
ones_array = np.ones((2, 4))
print(ones_array)

# Create an array with a range of values
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)

# Create an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # Start, stop, number of points
print(linspace_array)

# Get the data type of an array
print(my_array.dtype)

# Get the number of dimensions of an array
print(b.ndim)

# Get the total number of elements in an array
print(b.size)

# Reshape an array
reshaped_array = b.reshape(2, 4)
print(reshaped_array)

# Transpose an array
transposed_array = b.T
print(transposed_array)

# Flatten an array
flattened_array = b.flatten()
print(flattened_array)

# Access elements using slicing
sliced_array = b[0:2, 1:3]
print(sliced_array)


# Perform element-wise operations
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

added_array = array1 + array2
print(added_array)

subtracted_array = array1 - array2
print(subtracted_array)

multiplied_array = array1 * array2
print(multiplied_array)

divided_array = array1 / array2
print(divided_array)

# Perform matrix multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(matrix1, matrix2)
matrix_product


# You can explore more attributes and functions using the NumPy documentation.


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
int64
2
8
[[1 2 3 4]
 [4 5 6 7]]
[[1 3 4 6]
 [2 4 5 7]]
[1 2 3 4 4 5 6 7]
[[2]
 [4]]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


array([[19, 22],
       [43, 50]])

In [50]:
# prompt: array  attributes

import numpy as np
import pandas as pd

# Example array
a = np.array([1, 2, 3, 4])

# Common array attributes
print("Shape:", a.shape)  # Dimensions of the array (e.g., (4,) for a 1D array with 4 elements)
print("Size:", a.size)    # Total number of elements in the array
print("Data type:", a.dtype)  # Data type of the elements in the array (e.g., int32, float64)
print("Number of dimensions:", a.ndim)  # Number of dimensions (e.g., 1 for a 1D array)

# Other useful attributes
# a.itemsize  # Size of each element in bytes
# a.nbytes  # Total size of the array in bytes

# Reshaping arrays
b = np.array([(1, 2, 3, 4), (4, 5, 6, 7)])
print("Original shape:", b.shape)
b = b.reshape(4, 2)
print("Reshaped shape:", b.shape)

# Accessing elements
print("Element at (0, 1):", b[0, 1])

# Mathematical operations
print("Sum of elements:", a.sum())
print("Product of elements:", a.prod())
print("Minimum element:", a.min())
print("Maximum element:", a.max())

# Axis-wise operations
c = np.array([(1, 2, 3, 4), (4, 5, 6, 7)])
print("Sum along axis 0:", c.sum(axis=0))  # Sum of each column
print("Sum along axis 1:", c.sum(axis=1))  # Sum of each row


# For Pandas DataFrames
df = pd.DataFrame({'col1': ['A', 'B', 'B', 'A'], 'col2': [1, 2, 2, 3]})

# Check for duplicates
print("Duplicated rows:", df.duplicated())

# Drop duplicates
df1 = df.drop_duplicates()
print("DataFrame after dropping duplicates:\n", df1)

# Reset index after dropping duplicates
df2 = df1.reset_index()
print("DataFrame after resetting index:\n", df2)

# Drop the 'index' column
df3 = df2.drop('index', axis=1)
print("DataFrame after dropping 'index' column:\n", df3)

# More array operations:
# Transpose, flatten, slicing, element-wise operations, matrix multiplication (using np.dot)

Shape: (4,)
Size: 4
Data type: int64
Number of dimensions: 1
Original shape: (2, 4)
Reshaped shape: (4, 2)
Element at (0, 1): 2
Sum of elements: 10
Product of elements: 24
Minimum element: 1
Maximum element: 4
Sum along axis 0: [ 5  7  9 11]
Sum along axis 1: [10 22]
Duplicated rows: 0    False
1    False
2     True
3    False
dtype: bool
DataFrame after dropping duplicates:
   col1  col2
0    A     1
1    B     2
3    A     3
DataFrame after resetting index:
    index col1  col2
0      0    A     1
1      1    B     2
2      3    A     3
DataFrame after dropping 'index' column:
   col1  col2
0    A     1
1    B     2
2    A     3


In [51]:
# prompt: integer indexing  , array indexing

# Integer indexing and array indexing examples

# Create a NumPy array
my_array = np.array([10, 20, 30, 40, 50])

# Integer indexing: Accessing elements by their position
element_at_index_2 = my_array[2]  # Access the element at index 2 (which is 30)
print("Element at index 2:", element_at_index_2)

# Array indexing: Accessing multiple elements using a list of indices
indices_to_access = [0, 3, 4]
elements_at_indices = my_array[indices_to_access]  # Access elements at indices 0, 3, and 4
print("Elements at selected indices:", elements_at_indices)

# Boolean array indexing: Accessing elements based on a boolean condition
boolean_condition = my_array > 30
elements_greater_than_30 = my_array[boolean_condition]
print("Elements greater than 30:", elements_greater_than_30)

# Slicing: Accessing a range of elements
elements_from_1_to_3 = my_array[1:4]  # Access elements from index 1 (inclusive) to 4 (exclusive)
print("Elements from index 1 to 3:", elements_from_1_to_3)

# Modifying elements using integer indexing
my_array[1] = 25  # Change the element at index 1 to 25
print("Modified array:", my_array)

# Multi-dimensional array indexing

# Create a 2D array
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements in a 2D array
element_at_row_1_col_2 = my_2d_array[1, 2]  # Access the element at row 1, column 2 (which is 6)
print("Element at row 1, column 2:", element_at_row_1_col_2)

# Accessing a row
row_2 = my_2d_array[2]  # Access the entire second row
print("Row 2:", row_2)


# Accessing a column
column_1 = my_2d_array[:, 0]  # Access the entire first column
print("Column 1:", column_1)

# Modifying elements in a 2D array
my_2d_array[0, 0] = 10  # Change the element at row 0, column 0 to 10
print("Modified 2D array:\n", my_2d_array)



Element at index 2: 30
Elements at selected indices: [10 40 50]
Elements greater than 30: [40 50]
Elements from index 1 to 3: [20 30 40]
Modified array: [10 25 30 40 50]
Element at row 1, column 2: 6
Row 2: [7 8 9]
Column 1: [1 4 7]
Modified 2D array:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# prompt: boolean array indexing examples , 10 examples

import numpy as np

# Example 1: Selecting elements greater than 5
arr = np.array([1, 7, 3, 9, 4, 6])
mask = arr > 5
result = arr[mask]
print("Example 1:", result)  # Output: [7 9 6]


# Example 2: Selecting even numbers
arr = np.array([2, 5, 8, 1, 10, 3])
mask = arr % 2 == 0
result = arr[mask]
print("Example 2:", result)  # Output: [2 8 10]


# Example 3: Selecting elements within a range
arr = np.array([12, 5, 8, 15, 10, 3])
mask = (arr > 5) & (arr < 12)
result = arr[mask]
print("Example 3:", result)  # Output: [8 10]


# Example 4: Selecting elements based on multiple conditions
arr = np.array([2, 5, 8, 1, 10, 3])
mask = (arr % 2 == 0) | (arr > 7)
result = arr[mask]
print("Example 4:", result)  # Output: [2 8 10]


# Example 5: Selecting elements in a 2D array based on a condition
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = arr > 5
result = arr[mask]
print("Example 5:", result)  # Output: [6 7 8 9]


# Example 6: Combining boolean indexing with slicing
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr % 2 == 0
result = arr[mask][1:3]
print("Example 6:", result)  # Output: [4 6]


# Example 7: Modifying elements based on a condition
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3] = 0
print("Example 7:", arr)  # Output: [1 2 3 0 0]



# Example 8: Using boolean indexing with a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28]}
df = pd.DataFrame(data)
mask = df['Age'] > 25
result = df[mask]
print("Example 8:\n", result)  # Output: DataFrame with rows where Age > 25



# Example 9: Using boolean indexing with a multi-dimensional array
arr = np.array([[1, 2], [3, 4], [5, 6]])
mask = arr[:, 0] > 3
result = arr[mask]
print("Example 9:", result)  # Output: [[3 4] [5 6]]



# Example 10: Using ~ operator to negate a condition
arr = np.array([1, 2, 3, 4, 5])
mask = arr < 3
result = arr[~mask]
print("Example 10:", result)  # Output: [3 4 5]



In [56]:
arr =np.array([[1,2],[3,4],[5,6]])
bool_arr = arr[:,0] > 3
print(arr[bool_arr])

[[5 6]]


In [57]:
bool_arr = arr[:, 0] > 3

In [58]:
bool_arr

array([False, False,  True])

In [59]:
arr. e

(3, 2)

In [60]:
print(arr[bool_arr])

[[5 6]]


In [61]:
# prompt: boolean indexing new  examples, give 5 , think differently

# Example 1: Selecting rows in a DataFrame where a specific column value is not NaN
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1, 2, np.nan, 4, 5], 'B': [6, 7, 8, 9, 10]})
mask = df['A'].notna()
result = df[mask]
print("Example 1:\n", result)


# Example 2: Selecting elements from a NumPy array based on a string condition
arr = np.array(['apple', 'banana', 'orange', 'grape'])
mask = np.char.startswith(arr, 'a')
result = arr[mask]
print("Example 2:", result)


# Example 3: Selecting rows in a DataFrame where a column contains a specific substring
df = pd.DataFrame({'Name': ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'David Lee'],
                   'Age': [25, 30, 22, 28]})
mask = df['Name'].str.contains('Smith')
result = df[mask]
print("Example 3:\n", result)


# Example 4: Selecting elements from a NumPy array where a condition based on a function is met
arr = np.array([1, 2, 3, 4, 5])
def is_even(x):
  return x % 2 == 0

mask = np.vectorize(is_even)(arr)
result = arr[mask]
print("Example 4:", result)


# Example 5: Selecting rows in a DataFrame where a column value is within a specified range of dates
df = pd.DataFrame({'Date': pd.to_datetime(['2023-10-26', '2023-10-27', '2023-10-28', '2023-10-29']),
                   'Value': [10, 12, 15, 18]})
start_date = pd.to_datetime('2023-10-27')
end_date = pd.to_datetime('2023-10-29')
mask = (df['Date'] >= start_date) & (df['Date'] <= end_date)
result = df[mask]
print("Example 5:\n", result)

Example 1:
      A   B
0  1.0   6
1  2.0   7
3  4.0   9
4  5.0  10
Example 2: ['apple']
Example 3:
           Name  Age
0  Alice Smith   25
Example 4: [2 4]
Example 5:
         Date  Value
1 2023-10-27     12
2 2023-10-28     15
3 2023-10-29     18


In [63]:
import pandas as pd
df = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})
bool_arr = df['A'] > 1
print(df[bool_arr])
bool_arr

   A  B
1  2  5
2  3  6


0    False
1     True
2     True
Name: A, dtype: bool

In [65]:
# prompt: slicing and iterating in arrays ,give 10 examples

# Example 1: Slicing a 1D array
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4]  # Elements from index 1 to 3 (exclusive)
print("Example 1:", sliced_arr)

# Example 2: Slicing a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sliced_arr_2d = arr_2d[0:2, 1:3]  # Rows 0 and 1, columns 1 and 2
print("Example 2:\n", sliced_arr_2d)

# Example 3: Iterating through a 1D array
arr = np.array([10, 20, 30])
for element in arr:
  print("Example 3:", element)

# Example 4: Iterating through a 2D array using nested loops
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
for row in arr_2d:
  for element in row:
    print("Example 4:", element)


# Example 5: Iterating through a 2D array using nditer
arr_2d = np.array([[1, 2], [3, 4]])
for element in np.nditer(arr_2d):
  print("Example 5:", element)


# Example 6: Slicing with a step
arr = np.array([1, 2, 3, 4, 5, 6])
sliced_arr = arr[1:5:2]  # Elements from index 1 to 4 with a step of 2
print("Example 6:", sliced_arr)


# Example 7: Slicing with negative indices
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[-3:-1]  # Elements from the third-to-last to the second-to-last
print("Example 7:", sliced_arr)


# Example 8: Slicing with a stride
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[::2]  # Every other element
print("Example 8:", sliced_arr)


# Example 9: Iterating through a NumPy array using enumerate
arr = np.array([1, 2, 3, 4, 5])
for index, element in enumerate(arr):
  print("Example 9: Index:", index, "Element:", element)


# Example 10: Iterating through rows of a DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
for index, row in df.iterrows():
  print("Example 10: Index:", index, "Row:", row.to_dict())


Example 1: [2 3 4]
Example 2:
 [[2 3]
 [5 6]]
Example 3: 10
Example 3: 20
Example 3: 30
Example 4: 1
Example 4: 2
Example 4: 3
Example 4: 4
Example 4: 5
Example 4: 6
Example 5: 1
Example 5: 2
Example 5: 3
Example 5: 4
Example 6: [2 4]
Example 7: [3 4]
Example 8: [1 3 5 7 9]
Example 9: Index: 0 Element: 1
Example 9: Index: 1 Element: 2
Example 9: Index: 2 Element: 3
Example 9: Index: 3 Element: 4
Example 9: Index: 4 Element: 5
Example 10: Index: 0 Row: {'A': 1, 'B': 4}
Example 10: Index: 1 Row: {'A': 2, 'B': 5}
Example 10: Index: 2 Row: {'A': 3, 'B': 6}


In [66]:
# prompt: slicing and iterating some more 5 examples, think differently

# Example 1: Slicing a Pandas DataFrame to select specific rows and columns
df = pd.DataFrame({'A': [1, 2, 3, 4, 5], 'B': [6, 7, 8, 9, 10], 'C': [11, 12, 13, 14, 15]})
sliced_df = df.loc[1:3, ['A', 'C']]  # Rows 1 to 3, columns 'A' and 'C'
print("Example 1:\n", sliced_df)


# Example 2: Iterating through rows of a Pandas DataFrame with specific column values
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28]})
for index, row in df.iterrows():
  if row['Age'] > 25:
    print("Example 2: Name:", row['Name'], "Age:", row['Age'])


# Example 3: Slicing a NumPy array to extract a submatrix
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
submatrix = arr[1:, 0:2]  # Rows 1 and 2, columns 0 and 1
print("Example 3:\n", submatrix)


# Example 4: Iterating through a NumPy array with a specific condition
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
for element in arr:
  if element % 2 == 0:
    print("Example 4: Even number:", element)


# Example 5: Slicing a Pandas Series to select a specific range of values
series = pd.Series([10, 20, 30, 40, 50])
sliced_series = series[1:4]  # Elements from index 1 to 3 (exclusive)
print("Example 5:\n", sliced_series)

Example 1:
    A   C
1  2  12
2  3  13
3  4  14
Example 2: Name: Bob Age: 30
Example 2: Name: David Age: 28
Example 3:
 [[4 5]
 [7 8]]
Example 4: Even number: 2
Example 4: Even number: 4
Example 4: Even number: 6
Example 4: Even number: 8
Example 4: Even number: 10
Example 5:
 1    20
2    30
3    40
dtype: int64


In [67]:
# prompt: basic artithematic operationsin numpy, give 10 examples

# Example 1: Addition
result_add = np.array([1, 2, 3]) + np.array([4, 5, 6])
print("Addition:", result_add)

# Example 2: Subtraction
result_sub = np.array([10, 8, 6]) - np.array([2, 4, 6])
print("Subtraction:", result_sub)

# Example 3: Multiplication
result_mul = np.array([2, 3, 4]) * np.array([5, 6, 7])
print("Multiplication:", result_mul)

# Example 4: Division
result_div = np.array([12, 18, 24]) / np.array([2, 3, 4])
print("Division:", result_div)

# Example 5: Exponentiation
result_exp = np.array([2, 3, 4]) ** 2
print("Exponentiation:", result_exp)

# Example 6: Modulus
result_mod = np.array([10, 11, 12]) % 3
print("Modulus:", result_mod)

# Example 7: Floor division
result_floor_div = np.array([15, 16, 17]) // 4
print("Floor Division:", result_floor_div)

# Example 8: Square root
result_sqrt = np.sqrt(np.array([4, 9, 16]))
print("Square Root:", result_sqrt)

# Example 9: Sine
result_sin = np.sin(np.array([0, np.pi / 2, np.pi]))
print("Sine:", result_sin)

# Example 10: Cosine
result_cos = np.cos(np.array([0, np.pi / 2, np.pi]))
print("Cosine:", result_cos)

Addition: [5 7 9]
Subtraction: [8 4 0]
Multiplication: [10 18 28]
Division: [6. 6. 6.]
Exponentiation: [ 4  9 16]
Modulus: [1 2 0]
Floor Division: [3 4 4]
Square Root: [2. 3. 4.]
Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [68]:
# prompt: more examples for arithematic operation , think differently

# Example 11: Logarithm (base 10)
result_log10 = np.log10(np.array([1, 10, 100]))
print("Logarithm (base 10):", result_log10)

# Example 12: Natural logarithm (base e)
result_ln = np.log(np.array([1, np.e, np.e**2]))
print("Natural Logarithm:", result_ln)

# Example 13: Absolute value
result_abs = np.abs(np.array([-5, 0, 5]))
print("Absolute Value:", result_abs)

# Example 14: Rounding to the nearest integer
result_round = np.round(np.array([1.2, 2.7, 3.5]))
print("Rounding:", result_round)

# Example 15: Ceiling (smallest integer greater than or equal to the input)
result_ceil = np.ceil(np.array([1.2, 2.7, 3.5]))
print("Ceiling:", result_ceil)

# Example 16: Floor (largest integer less than or equal to the input)
result_floor = np.floor(np.array([1.2, 2.7, 3.5]))
print("Floor:", result_floor)

# Example 17: Element-wise maximum
result_maximum = np.maximum(np.array([1, 3, 5]), np.array([2, 4, 6]))
print("Element-wise Maximum:", result_maximum)

# Example 18: Element-wise minimum
result_minimum = np.minimum(np.array([1, 3, 5]), np.array([2, 4, 6]))
print("Element-wise Minimum:", result_minimum)


# Example 19: Element-wise comparison (greater than)
result_greater_than = np.array([1, 3, 5]) > np.array([2, 4, 6])
print("Element-wise Greater Than:", result_greater_than)

# Example 20: Element-wise comparison (less than or equal to)
result_less_than_or_equal_to = np.array([1, 3, 5]) <= np.array([2, 4, 6])
print("Element-wise Less Than or Equal To:", result_less_than_or_equal_to)

Logarithm (base 10): [0. 1. 2.]
Natural Logarithm: [0. 1. 2.]
Absolute Value: [5 0 5]
Rounding: [1. 3. 4.]
Ceiling: [2. 3. 4.]
Floor: [1. 2. 3.]
Element-wise Maximum: [2 4 6]
Element-wise Minimum: [1 3 5]
Element-wise Greater Than: [False False False]
Element-wise Less Than or Equal To: [ True  True  True]
